class partHistoria{
    constructor(fecha, rival, torneo, cancha, gCAT, gRival, result){


        this.fecha = fecha,
        this.rival = rival,
        this.torneo = torneo,
        this.cancha = cancha,
        this.gCAT = gCAT,
        this.gRival = gRival,
        this.result = result
    }
}

encuentrosHistorico.push(new partHistoria('06.01.1932','Atlanta','Primera Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('31.05.1931','Estudiantes (LP)','Primera Division','Estudiantes (LP)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.06.1931','San Lorenzo','Primera Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('07.06.1931','River Plate','Primera Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('14.06.1931','Chacarita Juniors','Primera Division','Atlanta',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('28.06.1931','Gimnasia (LP)','Primera Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('05.07.1931','Quilmes','Primera Division','Quilmes',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('09.07.1931','Ferro Carril Oeste','Primera Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('12.07.1931','Independiente','Primera Division','Independiente',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('19.07.1931','Platense','Primera Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('26.07.1931','Tigre','Primera Division','Tigre',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('02.08.1931','Vélez Sarsfield','Primera Division','Vélez Sarsfield',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('09.08.1931','Racing Club','Primera Division','River Plate',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('16.08.1931','Argentinos Juniors','Primera Division','Argentinos Juniors',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('30.08.1931','Huracán (BA)','Primera Division','Talleres (RE)',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('05.09.1931','Lanús','Primera Division','Lanús',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('12.09.1931','Boca Juniors','Primera Division','River Plate',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('20.09.1931','Atlanta','Primera Division','San Lorenzo',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('26.09.1931','Estudiantes (LP)','Primera Division','River Plate',4,4,'empate'));
encuentrosHistorico.push(new partHistoria('04.10.1931','San Lorenzo','Primera Division','San Lorenzo',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('11.10.1931','River Plate','Primera Division','River Plate',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('18.10.1931','Chacarita Juniors','Primera Division','Talleres (RE)',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('25.10.1931','Gimnasia (LP)','Primera Division','Gimnasia (LP)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('01.11.1931','Quilmes','Primera Division','Talleres (RE)',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('11.11.1931','Ferro Carril Oeste','Primera Division','Ferro Carril Oeste',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('15.11.1931','Independiente','Primera Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('22.11.1931','Platense','Primera Division','Platense',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('29.11.1931','Tigre','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('06.12.1931','Vélez Sarsfield','Primera Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('08.12.1931','Racing Club','Primera Division','Racing Club',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('13.12.1931','Argentinos Juniors','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('20.12.1931','Huracán (BA)','Primera Division','Huracán (BA)',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('27.12.1931','Lanús','Primera Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('02.01.1932','Boca Juniors','Primera Division','Boca Juniors',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('13.03.1932','Tigre','Primera Division','Tigre',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('20.03.1932','Argentinos Juniors','Primera Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('26.03.1932','Estudiantes (LP)','Primera Division','Estudiantes (LP)',4,6,'derrota'));
encuentrosHistorico.push(new partHistoria('10.04.1932','Ferro Carril Oeste','Primera Division','Talleres (RE)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('17.04.1932','Quilmes','Primera Division','Quilmes',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('24.04.1932','Platense','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('01.05.1932','Gimnasia (LP)','Primera Division','Gimnasia (LP)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('05.05.1932','Vélez Sarsfield','Primera Division','Talleres (RE)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('09.05.1932','Lanús','Primera Division','Lanús',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('15.05.1932','River Plate','Primera Division','River Plate',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('22.05.1932','Racing Club','Primera Division','Talleres (RE)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('29.05.1932','Huracán (BA)','Primera Division','Huracán (BA)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('05.06.1932','Atlanta','Primera Division','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.06.1932','Boca Juniors','Primera Division','Boca Juniors',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('19.06.1932','Independiente','Primera Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('26.06.1932','San Lorenzo','Primera Division','San Lorenzo',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('10.07.1932','Chacarita Juniors','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('24.07.1932','Tigre','Primera Division','Talleres (RE)',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('31.07.1932','Argentinos Juniors','Primera Division','Argentinos Juniors',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('07.08.1932','Estudiantes (LP)','Primera Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('14.08.1932','Ferro Carril Oeste','Primera Division','Ferro Carril Oeste',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.08.1932','Quilmes','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('28.08.1932','Platense','Primera Division','Platense',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('04.09.1932','Gimnasia (LP)','Primera Division','Platense',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('11.09.1932','Vélez Sarsfield','Primera Division','Vélez Sarsfield',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('18.09.1932','Lanús','Primera Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('25.09.1932','River Plate','Primera Division','Talleres (RE)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('02.10.1932','Racing Club','Primera Division','Racing Club',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('09.10.1932','Huracán (BA)','Primera Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('16.10.1932','Atlanta','Primera Division','Argentinos Juniors',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('23.10.1932','Boca Juniors','Primera Division','Talleres (RE)',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('31.10.1932','Independiente','Primera Division','Independiente',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('06.11.1932','San Lorenzo','Primera Division','Talleres (RE)',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('13.11.1932','Chacarita Juniors','Primera Division','River Plate',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('06.03.1933','Platense','Primera Division','Platense',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('12.03.1933','Huracán (BA)','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('19.03.1933','Quilmes','Primera Division','Boca Juniors',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('02.04.1933','Estudiantes (LP)','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('06.04.1933','Tigre','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('09.04.1933','Vélez Sarsfield','Primera Division','Vélez Sarsfield',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('23.04.1933','Argentinos Juniors','Primera Division','Platense',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('30.04.1933','Gimnasia (LP)','Primera Division','Talleres (RE)',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('07.05.1933','Ferro Carril Oeste','Primera Division','Boca Juniors',4,4,'empate'));
encuentrosHistorico.push(new partHistoria('14.05.1933','Atlanta','Primera Division','Talleres (RE)',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('21.05.1933','Chacarita Juniors','Primera Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('28.05.1933','Boca Juniors','Primera Division','River Plate',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.06.1933','Independiente','Primera Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('11.06.1933','San Lorenzo','Primera Division','San Lorenzo',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('18.06.1933','Lanús','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('25.06.1933','River Plate','Primera Division','River Plate',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('02.07.1933','Racing Club','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('16.07.1933','Huracán (BA)','Primera Division','Huracán (BA)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('23.07.1933','Quilmes','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('30.07.1933','Platense','Primera Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('06.08.1933','Estudiantes (LP)','Primera Division','Estudiantes (LP)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('13.08.1933','Vélez Sarsfield','Primera Division','Talleres (RE)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('20.08.1933','Tigre','Primera Division','Tigre',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('27.08.1933','Argentinos Juniors','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('03.09.1933','Gimnasia (LP)','Primera Division','Gimnasia (LP)',1,7,'derrota'));
encuentrosHistorico.push(new partHistoria('10.09.1933','Ferro Carril Oeste','Primera Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('01.10.1933','Atlanta','Primera Division','Atlanta',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('08.10.1933','Chacarita Juniors','Primera Division','Chacarita Juniors',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('15.10.1933','Boca Juniors','Primera Division','Talleres (RE)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('22.10.1933','Independiente','Primera Division','Independiente',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('29.10.1933','San Lorenzo','Primera Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('05.11.1933','Lanús','Primera Division','Boca Juniors',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('12.11.1933','River Plate','Primera Division','Talleres (RE)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('19.11.1933','Racing Club','Primera Division','Racing Club',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('17.03.1935','San Lorenzo','Primera Division','Talleres (RE)',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('24.03.1935','Lanús','Primera Division','Lanús',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('07.04.1935','Vélez Sarsfield','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('14.04.1935','Huracán (BA)','Primera Division','Huracán (BA)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('21.04.1935','Gimnasia (LP)','Primera Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('28.04.1935','Ferro Carril Oeste','Primera Division','Ferro Carril Oeste',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('05.05.1935','Argentinos Juniors','Primera Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('12.05.1935','Estudiantes (LP)','Primera Division','Estudiantes (LP)',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('19.05.1935','Atlanta','Primera Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('26.05.1935','Platense','Primera Division','Platense',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('02.06.1935','River Plate','Primera Division','Talleres (RE)',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('09.06.1935','Chacarita Juniors','Primera Division','Chacarita Juniors',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('16.06.1935','Racing Club','Primera Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('23.06.1935','Tigre','Primera Division','Argentinos Juniors',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('30.06.1935','Quilmes','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('21.07.1935','Independiente','Primera Division','Independiente',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('28.07.1935','Boca Juniors','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('04.08.1935','San Lorenzo','Primera Division','San Lorenzo',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('11.08.1935','Lanús','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('18.08.1935','Vélez Sarsfield','Primera Division','Vélez Sarsfield',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('25.08.1935','Huracán (BA)','Primera Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('01.09.1935','Gimnasia (LP)','Primera Division','Gimnasia (LP)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('08.09.1935','Ferro Carril Oeste','Primera Division','Talleres (RE)',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('15.09.1935','Argentinos Juniors','Primera Division','Argentinos Juniors',4,4,'empate'));
encuentrosHistorico.push(new partHistoria('22.09.1935','Estudiantes (LP)','Primera Division','River Plate',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('06.10.1935','Atlanta','Primera Division','Atlanta',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('06.10.1935','Platense','Primera Division','River Plate',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('07.10.1935','Chacarita Juniors','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('20.10.1935','River Plate','Primera Division','River Plate',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('11.11.1935','Racing Club','Primera Division','Racing Club',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('01.12.1935','Tigre','Primera Division','Talleres (RE)',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('08.12.1935','Quilmes','Primera Division','Quilmes',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('19.12.1935','Independiente','Primera Division','Talleres (RE)',2,6,'derrota'));
encuentrosHistorico.push(new partHistoria('22.12.1935','Boca Juniors','Primera Division','Boca Juniors',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('05.04.1936','Lanús','Copa de Honor','Lanús',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.04.1936','Boca Juniors','Copa de Honor','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('19.04.1936','Huracán (BA)','Copa de Honor','Huracán (BA)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('26.04.1936','Ferro Carril Oeste','Copa de Honor','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('03.05.1936','Chacarita Juniors','Copa de Honor','Chacarita Juniors',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('10.05.1936','Argentinos Juniors','Copa de Honor','Talleres (RE)',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('17.05.1936','Racing Club','Copa de Honor','Racing Club',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('24.05.1936','Gimnasia (LP)','Copa de Honor','Talleres (RE)',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('31.05.1936','Tigre','Copa de Honor','Platense',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('07.06.1936','River Plate','Copa de Honor','River Plate',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('14.06.1936','San Lorenzo','Copa de Honor','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.06.1936','Vélez Sarsfield','Copa de Honor','Vélez Sarsfield',1,6,'derrota'));
encuentrosHistorico.push(new partHistoria('23.06.1936','Platense','Copa de Honor','Talleres (RE)','x','x','empate'));
encuentrosHistorico.push(new partHistoria('28.06.1936','Atlanta','Copa de Honor','Atlanta','x','x','empate'));
encuentrosHistorico.push(new partHistoria('05.07.1936','Quilmes','Copa de Honor','Talleres (RE)','x','x','empate'));
encuentrosHistorico.push(new partHistoria('12.07.1936','Independiente','Copa de Honor','Independiente','x','x','empate'));
encuentrosHistorico.push(new partHistoria('26.07.1936','Estudiantes (LP)','Copa de Honor','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('16.08.1936','Lanús','Copa Campeonato','Talleres (RE)',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('23.08.1936','Boca Juniors','Copa Campeonato','Boca Juniors',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('30.08.1936','Huracán (BA)','Copa Campeonato','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('06.09.1936','Ferro Carril Oeste','Copa Campeonato','Ferro Carril Oeste',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('13.09.1936','Chacarita Juniors','Copa Campeonato','Talleres (RE)',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('20.09.1936','Argentinos Juniors','Copa Campeonato','Argentinos Juniors',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.10.1936','Racing Club','Copa Campeonato','Talleres (RE)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('19.10.1936','Gimnasia (LP)','Copa Campeonato','Gimnasia (LP)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('25.10.1936','Tigre','Copa Campeonato','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('01.11.1936','River Plate','Copa Campeonato','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('08.11.1936','San Lorenzo','Copa Campeonato','San Lorenzo',1,6,'derrota'));
encuentrosHistorico.push(new partHistoria('11.11.1936','Vélez Sarsfield','Copa Campeonato','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('15.11.1936','Platense','Copa Campeonato','Platense',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('22.11.1936','Atlanta','Copa Campeonato','Talleres (RE)',5,5,'empate'));
encuentrosHistorico.push(new partHistoria('29.11.1936','Quilmes','Copa Campeonato','Quilmes',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('06.12.1936','Independiente','Copa Campeonato','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('14.12.1936','Estudiantes (LP)','Copa Campeonato','Estudiantes (LP)',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('04.04.1937','Argentinos Juniors','Primera Division','River Plate',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('11.04.1937','Boca Juniors','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('18.04.1937','Platense','Primera Division','Platense',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('02.05.1937','Chacarita Juniors','Primera Division','Talleres (RE)',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('16.05.1937','Lanús','Primera Division','Lanús',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('23.05.1937','Estudiantes (LP)','Primera Division','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('30.05.1937','Ferro Carril Oeste','Primera Division','Ferro Carril Oeste',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('06.06.1937','Huracán (BA)','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('13.06.1937','Quilmes','Primera Division','Quilmes',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('27.06.1937','River Plate','Primera Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.07.1937','Tigre','Primera Division','Tigre',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('11.07.1937','Atlanta','Primera Division','Lanús',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('18.07.1937','Independiente','Primera Division','Independiente',0,8,'derrota'));
encuentrosHistorico.push(new partHistoria('25.07.1937','Gimnasia (LP)','Primera Division','Gimnasia (LP)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('01.08.1937','Racing Club','Primera Division','San Lorenzo',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('07.08.1937','Vélez Sarsfield','Primera Division','Vélez Sarsfield',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('15.08.1937','San Lorenzo','Primera Division','Talleres (RE)',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('22.08.1937','Argentinos Juniors','Primera Division','Talleres (RE)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('29.08.1937','Boca Juniors','Primera Division','Boca Juniors',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('12.09.1937','Platense','Primera Division','Talleres (RE)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('19.09.1937','Chacarita Juniors','Primera Division','Chacarita Juniors',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('26.09.1937','Lanús','Primera Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('03.10.1937','Estudiantes (LP)','Primera Division','Estudiantes (LP)',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('17.10.1937','Ferro Carril Oeste','Primera Division','Talleres (RE)',4,3,'victoria'));
encuentrosHistorico.push(new partHistoria('24.10.1937','Huracán (BA)','Primera Division','Huracán (BA)',2,6,'derrota'));
encuentrosHistorico.push(new partHistoria('31.10.1937','Quilmes','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('07.11.1937','River Plate','Primera Division','River Plate',1,6,'derrota'));
encuentrosHistorico.push(new partHistoria('14.11.1937','Tigre','Primera Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('21.11.1937','Atlanta','Primera Division','Atlanta',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('28.11.1937','Independiente','Primera Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('05.12.1937','Gimnasia (LP)','Primera Division','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('08.12.1937','Racing Club','Primera Division','Racing Club',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('12.12.1937','Vélez Sarsfield','Primera Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('19.12.1937','San Lorenzo','Primera Division','San Lorenzo',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('03.04.1938','Huracán (BA)','Primera Division','Talleres (RE)',2,7,'derrota'));
encuentrosHistorico.push(new partHistoria('10.04.1938','Vélez Sarsfield','Primera Division','Vélez Sarsfield',2,6,'derrota'));
encuentrosHistorico.push(new partHistoria('24.04.1938','Chacarita Juniors','Primera Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('08.05.1938','Boca Juniors','Primera Division','Ferro Carril Oeste',1,7,'derrota'));
encuentrosHistorico.push(new partHistoria('15.05.1938','Platense','Primera Division','Talleres (RE)',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('22.05.1938','Estudiantes (LP)','Primera Division','Estudiantes (LP)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('29.05.1938','Lanús','Primera Division','Talleres (RE)',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('05.06.1938','Tigre','Primera Division','Tigre',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('12.06.1938','Independiente','Primera Division','Talleres (RE)',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('19.06.1938','San Lorenzo','Primera Division','San Lorenzo',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('26.06.1938','Almagro','Primera Division','Lanús',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('03.07.1938','Atlanta','Primera Division','Atlanta',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('17.07.1938','Ferro Carril Oeste','Primera Division','River Plate',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('31.07.1938','River Plate','Primera Division','River Plate',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('07.08.1938','Gimnasia (LP)','Primera Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.08.1938','Racing Club','Primera Division','Racing Club',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('28.08.1938','Huracán (BA)','Primera Division','Huracán (BA)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('04.09.1938','Vélez Sarsfield','Primera Division','Talleres (RE)',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('11.09.1938','Chacarita Juniors','Primera Division','Chacarita Juniors',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('18.09.1938','Boca Juniors','Primera Division','Talleres (RE)',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('25.09.1938','Platense','Primera Division','Platense',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('02.10.1938','Estudiantes (LP)','Primera Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('09.10.1938','Lanús','Primera Division','Lanús',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('16.10.1938','Tigre','Primera Division','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('23.10.1938','Independiente','Primera Division','Independiente',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('30.10.1938','San Lorenzo','Primera Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('06.11.1938','Almagro','Primera Division','Vélez Sarsfield',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('13.11.1938','Atlanta','Primera Division','Talleres (RE)',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('20.11.1938','Ferro Carril Oeste','Primera Division','Ferro Carril Oeste',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('27.11.1938','River Plate','Primera Division','Talleres (RE)',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('04.12.1938','Gimnasia (LP)','Primera Division','Gimnasia (LP)',2,6,'derrota'));
encuentrosHistorico.push(new partHistoria('18.12.1938','Racing Club','Primera Division','Talleres (RE)',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('01.04.1939','Atlanta (B)','Segunda Division','Talleres (RE)',8,5,'victoria'));
encuentrosHistorico.push(new partHistoria('08.04.1939','Ferro Carril Oeste (B)','Segunda Division','Ferro Carril Oeste (B)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('15.04.1939','Defensores de Belgrano','Segunda Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('22.04.1939','Estudiantes (Bs.As.)','Segunda Division','Estudiantes (Bs.As.)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('29.04.1939','Los Andes','Segunda Division','Talleres (RE)',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('06.05.1939','Sportivo Buenos Aires','Segunda Division','Sportivo Buenos Aires',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('13.05.1939','Vélez Sarsfield (B)','Segunda Division','Vélez Sarsfield (B)',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('20.05.1939','Quilmes','Segunda Division','Talleres (RE)',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('27.05.1939','Huracán (BA)(B)','Segunda Division','Huracán (BA)(B)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('03.06.1939','Independiente (B)','Segunda Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('10.06.1939','Colegiales','Segunda Division','Colegiales',3,6,'derrota'));
encuentrosHistorico.push(new partHistoria('17.06.1939','Dock Sud','Segunda Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('01.07.1939','Estudiantes (LP)(B)','Segunda Division','Estudiantes (LP)(B)',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('15.07.1939','Tigre (B)','Segunda Division','Talleres (RE)',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('22.07.1939','Lanús (B)','Segunda Division','Lanús (B)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('29.07.1939','Platense (B)','Segunda Division','Talleres (RE)',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('05.08.1939','Boca Juniors (B)','Segunda Division','Boca Juniors (B)',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('19.08.1939','Chacarita Juniors (B)','Segunda Division','Talleres (RE)',4,3,'victoria'));
encuentrosHistorico.push(new partHistoria('30.08.1939','Argentinos Juniors','Segunda Division','Argentinos Juniors',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('02.09.1939','Excursionistas','Segunda Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('09.09.1939','All Boys','Segunda Division','All Boys',1,6,'derrota'));
encuentrosHistorico.push(new partHistoria('16.09.1939','Temperley','Segunda Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('23.09.1939','Argentino de Quilmes (B)','Segunda Division','Argentino de Quilmes (B)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('30.09.1939','San Lorenzo (B)','Segunda Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('14.10.1939','Racing Club (B)','Segunda Division','Racing Club (B)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.10.1939','Almagro','Segunda Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('28.10.1939','El Porvenir','Segunda Division','El Porvenir',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('04.11.1939','Barracas Central','Segunda Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('11.11.1939','Gimnasia (LP) (B)','Segunda Division','Gimnasia (LP) (B)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('25.11.1939','Acassuso','Segunda Division','Talleres (RE)',6,3,'victoria'));
encuentrosHistorico.push(new partHistoria('02.12.1939','Banfield','Segunda Division','Banfield',0,7,'derrota'));
encuentrosHistorico.push(new partHistoria('09.12.1939','River Plate (B)','Segunda Division','Talleres (RE)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('27.04.1940','Almagro','Segunda Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('04.05.1940','Argentinos Juniors','Segunda Division','Talleres (RE)',5,3,'victoria'));
encuentrosHistorico.push(new partHistoria('12.05.1940','Unión (Sta.Fe)','Segunda Division','Unión (Sta.Fe)',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('18.05.1940','Quilmes','Segunda Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('01.06.1940','Excursionistas','Segunda Division','Excursionistas',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('15.06.1940','Temperley','Segunda Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('22.06.1940','Boulogne','Segunda Division','Boulogne',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('29.06.1940','El Porvenir','Segunda Division','Talleres (RE)',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('06.07.1940','All Boys','Segunda Division','All Boys',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('13.07.1940','Barracas Central','Segunda Division','Talleres (RE)',6,4,'victoria'));
encuentrosHistorico.push(new partHistoria('03.08.1940','Colegiales','Segunda Division','Colegiales',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('10.08.1940','Argentino de Quilmes','Segunda Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('17.08.1940','Defensores de Belgrano','Segunda Division','Defensores de Belgrano',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('24.08.1940','Los Andes','Segunda Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('31.08.1940','Acassuso','Segunda Division','Acassuso',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('07.09.1940','Dock Sud','Segunda Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('25.09.1940','Estudiantes (Bs.As.)','Segunda Division','Estudiantes (Bs.As.)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('28.09.1940','Almagro','Segunda Division','Almagro',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('05.10.1940','Argentinos Juniors','Segunda Division','Argentinos Juniors',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('13.10.1940','Unión (Sta.Fe)','Segunda Division','Talleres (RE)',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('19.10.1940','Quilmes','Segunda Division','Quilmes',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('26.10.1940','Excursionistas','Segunda Division','Talleres (RE)',5,3,'victoria'));
encuentrosHistorico.push(new partHistoria('02.11.1940','Temperley','Segunda Division','Temperley',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('09.11.1940','Boulogne','Segunda Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('11.11.1940','El Porvenir','Segunda Division','El Porvenir',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('16.11.1940','All Boys','Segunda Division','Talleres (RE)',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('23.11.1940','Barracas Central','Segunda Division','Barracas Central',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('30.11.1940','Colegiales','Segunda Division','Talleres (RE)',5,2,'victoria'));
encuentrosHistorico.push(new partHistoria('11.12.1940','Argentino de Quilmes','Segunda Division','Argentino de Quilmes',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('14.12.1940','Defensores de Belgrano','Segunda Division','Talleres (RE)',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('18.12.1940','Los Andes','Segunda Division','Los Andes',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('21.12.1940','Acassuso','Segunda Division','Talleres (RE)',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('24.12.1940','Dock Sud','Segunda Division','Dock Sud',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('28.12.1940','Estudiantes (Bs.As.)','Segunda Division','Talleres (RE)',7,2,'victoria'));
encuentrosHistorico.push(new partHistoria('30.03.1941','Unión (Sta.Fe)','Segunda Division','Santa Fe',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('05.04.1941','Defensores de Belgrano','Segunda Division','Remedios de Escalada',8,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.04.1941','Los Andes','Segunda Division','Lomas de Zamora',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('19.04.1941','Vélez Sarsfield','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('26.04.1941','Acassuso','Segunda Division','San Isidro',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('03.05.1941','Dock Sud','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('10.05.1941','Almagro','Segunda Division','Villa Ortúzar',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('17.05.1941','Quilmes','Segunda Division','Quilmes',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('24.05.1941','Chacarita Juniors','Segunda Division','Remedios de Escalada',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('31.05.1941','Excursionistas','Segunda Division','Belgrano',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('07.06.1941','Temperley','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('14.06.1941','Argentinos Juniors','Segunda Division','Paternal',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('21.06.1941','All Boys','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('28.06.1941','Colegiales','Segunda Division','Colegiales',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('05.07.1941','Barracas Central','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.07.1941','Nueva Chicago','Segunda Division','Mataderos',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('19.07.1941','Argentino de Quilmes','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('26.07.1941','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('02.08.1941','Defensores de Belgrano','Segunda Division','Núñez',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('16.08.1941','Los Andes','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('23.08.1941','Vélez Sarsfield','Segunda Division','Villa Luro',1,7,'derrota'));
encuentrosHistorico.push(new partHistoria('30.08.1941','Acassuso','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('06.09.1941','Dock Sud','Segunda Division','Dock Sud',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('13.09.1941','Almagro','Segunda Division','Remedios de Escalada',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('20.09.1941','Quilmes','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('27.09.1941','Chacarita Juniors','Segunda Division','Villa Crespo',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('11.10.1941','Excursionistas','Segunda Division','Remedios de Escalada',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('18.10.1941','Temperley','Segunda Division','Temperley',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('25.10.1941','Argentinos Juniors','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('08.11.1941','All Boys','Segunda Division','Floresta',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('15.11.1941','Colegiales','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('22.11.1941','Barracas Central','Segunda Division','Barracas',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('29.11.1941','Nueva Chicago','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('06.12.1941','Argentino de Quilmes','Segunda Division','Quilmes',6,7,'derrota'));
encuentrosHistorico.push(new partHistoria('04.04.1942','Defensores de Belgrano','Segunda Division','Defensores de Belgrano',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('11.04.1942','Colegiales','Segunda Division','Talleres (RE)',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('18.04.1942','El Porvenir','Segunda Division','El Porvenir',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('02.05.1942','Almagro','Segunda Division','Talleres (RE)',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('09.05.1942','All Boys','Segunda Division','All Boys',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('16.05.1942','Dock Sud','Segunda Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('23.05.1942','Temperley','Segunda Division','Temperley',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('30.05.1942','Rosario Central','Segunda Division','Talleres (RE)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('06.06.1942','Excursionistas','Segunda Division','Excursionistas',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('13.06.1942','Acassuso','Segunda Division','Talleres (RE)',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('20.06.1942','Sportivo Alsina','Segunda Division','Sportivo Alsina',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('27.06.1942','Vélez Sarsfield','Segunda Division','Talleres (RE)',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.07.1942','Argentinos Juniors','Segunda Division','Argentinos Juniors',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('12.07.1942','Quilmes','Segunda Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('25.07.1942','Nueva Chicago','Segunda Division','Nueva Chicago',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('01.08.1942','Unión (Sta.Fe)','Segunda Division','Talleres (RE)',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('08.08.1942','Defensores de Belgrano','Segunda Division','Talleres (RE)',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('22.08.1942','Colegiales','Segunda Division','Colegiales',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('29.08.1942','El Porvenir','Segunda Division','Talleres (RE)',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('06.09.1942','Almagro','Segunda Division','Almagro',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('13.09.1942','All Boys','Segunda Division','Talleres (RE)',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('23.09.1942','Dock Sud','Segunda Division','Dock Sud',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('27.09.1942','Temperley','Segunda Division','Talleres (RE)',5,2,'victoria'));
encuentrosHistorico.push(new partHistoria('03.10.1942','Rosario Central','Segunda Division','Rosario Central',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('10.10.1942','Excursionistas','Segunda Division','Talleres (RE)',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('17.10.1942','Acassuso','Segunda Division','Acassuso',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('24.10.1942','Sportivo Alsina','Segunda Division','Talleres (RE)',8,3,'victoria'));
encuentrosHistorico.push(new partHistoria('31.10.1942','Vélez Sarsfield','Segunda Division','Vélez Sarsfield',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('07.11.1942','Argentinos Juniors','Segunda Division','Talleres (RE)',7,3,'victoria'));
encuentrosHistorico.push(new partHistoria('14.11.1942','Quilmes','Segunda Division','Quilmes',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('28.11.1942','Nueva Chicago','Segunda Division','Talleres (RE)',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('06.12.1942','Unión (Sta.Fe)','Segunda Division','Unión (Sta.Fe)',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('17.04.1943','Colegiales','Segunda Division','Colegiales',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('24.04.1943','Almagro','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('01.05.1943','Defensores de Belgrano','Segunda Division','Núñez',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('08.05.1943','Acassuso','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('15.05.1943','Argentino de Quilmes','Segunda Division','Quilmes',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('22.05.1943','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('29.05.1943','Nueva Chicago','Segunda Division','Mataderos',0,1,'derrota'));
encuentrosHistorico.push(new partHistoria('12.06.1943','Argentinos Juniors','Segunda Division','Paternal',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('19.06.1943','Dock Sud','Segunda Division','Remedios de Escalada',5,0,'victoria'));
encuentrosHistorico.push(new partHistoria('26.06.1943','Estudiantes (Bs.As.)','Segunda Division','Villa Devoto',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('03.07.1943','Excursionistas','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('11.07.1943','Vélez Sarsfield','Segunda Division','Liniers',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('17.07.1943','Tigre','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('24.07.1943','Quilmes','Segunda Division','Quilmes',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('31.07.1943','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('07.08.1943','Temperley','Segunda Division','Temperley',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('14.08.1943','All Boys','Segunda Division','Remedios de Escalada',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('21.08.1943','Colegiales','Segunda Division','Remedios de Escalada',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('28.08.1943','Almagro','Segunda Division','Villa Ortúzar',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('04.09.1943','Defensores de Belgrano','Segunda Division','Remedios de Escalada',6,2,'victoria'));
encuentrosHistorico.push(new partHistoria('11.09.1943','Acassuso','Segunda Division','San Isidro',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('18.09.1943','Argentino de Quilmes','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('25.09.1943','Central Córdoba (Ros)','Segunda Division','Rosario',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('02.10.1943','Nueva Chicago','Segunda Division','Remedios de Escalada',5,2,'victoria'));
encuentrosHistorico.push(new partHistoria('09.10.1943','Argentinos Juniors','Segunda Division','Remedios de Escalada',5,3,'victoria'));
encuentrosHistorico.push(new partHistoria('16.10.1943','Dock Sud','Segunda Division','Dock Sud',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('23.10.1943','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',3,6,'derrota'));
encuentrosHistorico.push(new partHistoria('30.10.1943','Excursionistas','Segunda Division','Belgrano',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('06.11.1943','Vélez Sarsfield','Segunda Division','Remedios de Escalada',3,6,'derrota'));
encuentrosHistorico.push(new partHistoria('13.11.1943','Tigre','Segunda Division','Victoria',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('20.11.1943','Quilmes','Segunda Division','Remedios de Escalada',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('27.11.1943','Unión (Sta.Fe)','Segunda Division','Santa Fe',1,5,'derrota'));
encuentrosHistorico.push(new partHistoria('04.12.1943','Temperley','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('11.12.1943','All Boys','Segunda Division','Floresta',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('15.04.1944','Tigre','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('22.04.1944','Los Andes','Segunda Division','Lomas de Zamora',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('29.04.1944','All Boys','Segunda Division','Remedios de Escalada',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('06.05.1944','Estudiantes (Bs.As.)','Segunda Division','Villa Devoto',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('13.05.1944','Gimnasia (LP)','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('20.05.1944','Tiro Federal','Segunda Division','Rosario',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('27.05.1944','Dock Sud','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('03.06.1944','Argentino de Rosario','Segunda Division','Rosario',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('10.06.1944','Almagro','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('20.06.1944','Defensores de Belgrano','Segunda Division','Núñez',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('24.06.1944','Acassuso','Segunda Division','Remedios de Escalada',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('01.07.1944','Temperley','Segunda Division','Temperley',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('08.07.1944','Nueva Chicago','Segunda Division','Remedios de Escalada',6,1,'victoria'));
encuentrosHistorico.push(new partHistoria('15.07.1944','Colegiales','Segunda Division','Colegiales',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('22.07.1944','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',7,2,'victoria'));
encuentrosHistorico.push(new partHistoria('29.07.1944','Quilmes','Segunda Division','Quilmes',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('05.08.1944','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('12.08.1944','Argentinos Juniors','Segunda Division','Paternal',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('19.08.1944','El Porvenir','Segunda Division','Remedios de Escalada',7,1,'victoria'));
encuentrosHistorico.push(new partHistoria('26.08.1944','Excursionistas','Segunda Division','Belgrano',4,3,'victoria'));
encuentrosHistorico.push(new partHistoria('30.08.1944','Tigre','Segunda Division','Victoria',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('02.09.1944','Los Andes','Segunda Division','Banfield',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('09.09.1944','All Boys','Segunda Division','Floresta',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('16.09.1944','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('23.09.1944','Gimnasia (LP)','Segunda Division','La Plata',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('30.09.1944','Tiro Federal','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('07.10.1944','Dock Sud','Segunda Division','Dock Sud',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('21.10.1944','Argentino de Rosario','Segunda Division','Remedios de Escalada',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('28.10.1944','Almagro','Segunda Division','Villa Ortúzar',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.11.1944','Defensores de Belgrano','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('11.11.1944','Acassuso','Segunda Division','San Isidro',3,7,'derrota'));
encuentrosHistorico.push(new partHistoria('18.11.1944','Temperley','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('25.11.1944','Nueva Chicago','Segunda Division','Mataderos',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('02.12.1944','Colegiales','Segunda Division','Remedios de Escalada',7,0,'victoria'));
encuentrosHistorico.push(new partHistoria('07.12.1944','Unión (Sta.Fe)','Segunda Division','Santa Fe',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('10.12.1944','Quilmes','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('16.12.1944','Central Córdoba (Ros)','Segunda Division','Rosario',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('24.12.1944','Argentinos Juniors','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('30.12.1944','El Porvenir','Segunda Division','Gerli',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('06.01.1945','Excursionistas','Segunda Division','Remedios de Escalada',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('17.03.1945','Banfield','Segunda Division','Banfield',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('24.03.1945','Acassuso','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('31.03.1945','Central Córdoba (Ros)','Segunda Division','Rosario',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('07.04.1945','Nueva Chicago','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('14.04.1945','Estudiantes (Bs.As.)','Segunda Division','Villa Crespo',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('21.04.1945','Dock Sud','Segunda Division','Remedios de Escalada',5,3,'victoria'));
encuentrosHistorico.push(new partHistoria('28.04.1945','Quilmes','Segunda Division','Quilmes',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('05.05.1945','Excursionistas','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('12.05.1945','Tiro Federal','Segunda Division','Rosario',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('19.05.1945','Los Andes','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('02.06.1945','Tigre','Segunda Division','Victoria',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('09.06.1945','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('16.06.1945','All Boys','Segunda Division','Floresta',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('23.06.1945','Almagro','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('30.06.1945','Argentinos Juniors','Segunda Division','Paternal',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('07.07.1945','El Porvenir','Segunda Division','Remedios de Escalada',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('14.07.1945','Barracas Central','Segunda Division','Barracas',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('21.07.1945','Defensores de Belgrano','Segunda Division','Remedios de Escalada',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('28.07.1945','Argentino de Rosario','Segunda Division','Rosario',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('04.08.1945','Temperley','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('11.08.1945','Banfield','Segunda Division','Remedios de Escalada',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('18.08.1945','Acassuso','Segunda Division','San Isidro',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('01.09.1945','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('08.09.1945','Nueva Chicago','Segunda Division','Mataderos',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('15.09.1945','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('22.09.1945','Dock Sud','Segunda Division','Dock Sud',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('29.09.1945','Quilmes','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('06.10.1945','Excursionistas','Segunda Division','Belgrano',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('13.10.1945','Tiro Federal','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('20.10.1945','Los Andes','Segunda Division','Lomas de Zamora',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('03.11.1945','Tigre','Segunda Division','Remedios de Escalada',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('11.11.1945','Unión (Sta.Fe)','Segunda Division','Santa Fe',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('17.11.1945','All Boys','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('24.11.1945','Almagro','Segunda Division','Villa Ortúzar',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('01.12.1945','Argentinos Juniors','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('08.12.1945','El Porvenir','Segunda Division','Lanús',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('16.12.1945','Barracas Central','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('22.12.1945','Defensores de Belgrano','Segunda Division','Núñez',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('29.12.1945','Argentino de Rosario','Segunda Division','Remedios de Escalada',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('05.01.1946','Temperley','Segunda Division','Temperley',5,5,'empate'));
encuentrosHistorico.push(new partHistoria('06.04.1946','Gimnasia (LP)','Segunda Division','Remedios de Escalada',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('13.04.1946','Temperley','Segunda Division','Temperley',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('20.04.1946','Acassuso','Segunda Division','Remedios de Escalada',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('27.04.1946','Dock Sud','Segunda Division','Dock Sud',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.05.1946','Excursionistas','Segunda Division','Remedios de Escalada',5,3,'victoria'));
encuentrosHistorico.push(new partHistoria('18.05.1946','Almagro','Segunda Division','Villa Ortúzar',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('25.05.1946','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',7,2,'victoria'));
encuentrosHistorico.push(new partHistoria('01.06.1946','Argentinos Juniors','Segunda Division','Paternal',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('08.06.1946','Tiro Federal','Segunda Division','Remedios de Escalada',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('15.06.1946','Argentino de Quilmes','Segunda Division','Quilmes',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('22.06.1946','Barracas Central','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('29.06.1946','Los Andes','Segunda Division','Lomas de Zamora',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('06.07.1946','El Porvenir','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('13.07.1946','Defensores de Belgrano','Segunda Division','Núñez',0,4,'derrota'));
encuentrosHistorico.push(new partHistoria('09.07.1946','Banfield','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('20.07.1946','Estudiantes (Bs.As.)','Segunda Division','Villa Crespo',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('27.07.1946','Argentino de Rosario','Segunda Division','Remedios de Escalada',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('03.08.1946','Nueva Chicago','Segunda Division','Mataderos',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('10.08.1946','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('17.08.1946','Quilmes','Segunda Division','Quilmes',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('24.08.1946','Gimnasia (LP)','Segunda Division','La Plata',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('31.08.1946','Temperley','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('07.09.1946','Acassuso','Segunda Division','Victoria',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.09.1946','Dock Sud','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('28.09.1946','Excursionistas','Segunda Division','Belgrano',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('12.10.1946','Almagro','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('19.10.1946','Central Córdoba (Ros)','Segunda Division','Rosario',3,5,'derrota'));
encuentrosHistorico.push(new partHistoria('26.10.1946','Argentinos Juniors','Segunda Division','Remedios de Escalada',6,2,'victoria'));
encuentrosHistorico.push(new partHistoria('09.11.1946','Tiro Federal','Segunda Division','Rosario',1,6,'derrota'));
encuentrosHistorico.push(new partHistoria('16.11.1946','Argentino de Quilmes','Segunda Division','Remedios de Escalada',5,2,'victoria'));
encuentrosHistorico.push(new partHistoria('23.11.1946','Barracas Central','Segunda Division','Barracas',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('30.11.1946','Los Andes','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('07.12.1946','El Porvenir','Segunda Division','Gerli',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('15.12.1946','Defensores de Belgrano','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('22.12.1946','Banfield','Segunda Division','Banfield',3,4,'derrota'));
encuentrosHistorico.push(new partHistoria('28.12.1946','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('08.01.1947','Argentino de Rosario','Segunda Division','Rosario',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('11.01.1947','Nueva Chicago','Segunda Division','Remedios de Escalada',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('18.01.1947','Unión (Sta.Fe)','Segunda Division','Santa Fe',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('25.01.1947','Quilmes','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('05.04.1947','Argentino de Rosario','Segunda Division','Remedios de Escalada',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('12.04.1947','Tiro Federal','Segunda Division','Rosario',2,4,'derrota'));
encuentrosHistorico.push(new partHistoria('19.04.1947','Defensores de Belgrano','Segunda Division','Remedios de Escalada',4,4,'empate'));
encuentrosHistorico.push(new partHistoria('26.04.1947','Estudiantes (Bs.As.)','Segunda Division','Villa Crespo',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('01.05.1947','Gimnasia (LP)','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('03.05.1947','Excursionistas','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('17.05.1947','Nueva Chicago','Segunda Division','Mataderos',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('24.05.1947','Quilmes','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('31.05.1947','Ferro Carril Oeste','Segunda Division','Caballito',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('07.06.1947','Temperley','Segunda Division','Remedios de Escalada',4,3,'victoria'));
encuentrosHistorico.push(new partHistoria('14.06.1947','Central Córdoba (Ros)','Segunda Division','Rosario',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('21.06.1947','Unión (Sta.Fe)','Segunda Division','Remedios de Escalada',5,2,'victoria'));
encuentrosHistorico.push(new partHistoria('28.06.1947','Almagro','Segunda Division','Villa Ortúzar',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('05.07.1947','Dock Sud','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.07.1947','El Porvenir','Segunda Division','Gerli',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('19.07.1947','Argentinos Juniors','Segunda Division','Remedios de Escalada',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('26.07.1947','Argentino de Quilmes','Segunda Division','Quilmes',6,4,'victoria'));
encuentrosHistorico.push(new partHistoria('02.08.1947','All Boys','Segunda Division','Remedios de Escalada',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('09.08.1947','Los Andes','Segunda Division','Lomas de Zamora',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('16.08.1947','Argentino de Rosario','Segunda Division','Rosario',0,3,'derrota'));
encuentrosHistorico.push(new partHistoria('23.08.1947','Tiro Federal','Segunda Division','Remedios de Escalada',6,0,'victoria'));
encuentrosHistorico.push(new partHistoria('30.08.1947','Defensores de Belgrano','Segunda Division','Núñez',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('06.09.1947','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',5,0,'victoria'));
encuentrosHistorico.push(new partHistoria('13.09.1947','Gimnasia (LP)','Segunda Division','La Plata',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('20.09.1947','Excursionistas','Segunda Division','Belgrano',4,4,'empate'));
encuentrosHistorico.push(new partHistoria('27.09.1947','Nueva Chicago','Segunda Division','Remedios de Escalada',1,3,'derrota'));
encuentrosHistorico.push(new partHistoria('04.10.1947','Quilmes','Segunda Division','Quilmes',0,5,'derrota'));
encuentrosHistorico.push(new partHistoria('11.10.1947','Ferro Carril Oeste','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('18.10.1947','Temperley','Segunda Division','Temperley',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('25.10.1947','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('01.11.1947','Unión (Sta.Fe)','Segunda Division','Santa Fe',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('08.11.1947','Almagro','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('15.11.1947','Dock Sud','Segunda Division','Dock Sud',1,1,'empate'));
encuentrosHistorico.push(new partHistoria('22.11.1947','El Porvenir','Segunda Division','Remedios de Escalada',6,0,'victoria'));
encuentrosHistorico.push(new partHistoria('29.11.1947','Argentinos Juniors','Segunda Division','Paternal',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('06.12.1947','Argentino de Quilmes','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.12.1947','All Boys','Segunda Division','Floresta',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('20.12.1947','Los Andes','Segunda Division','Remedios de Escalada',5,1,'victoria'));
encuentrosHistorico.push(new partHistoria('24.04.1948','Estudiantes (Bs.As.)','Segunda Division','Caballito',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('15.05.1948','Temperley','Segunda Division','Remedios de Escalada',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('29.05.1948','Tiro Federal','Segunda Division','Rosario',3,0,'victoria'));
encuentrosHistorico.push(new partHistoria('05.06.1948','All Boys','Segunda Division','Remedios de Escalada',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('12.06.1948','Argentinos Juniors','Segunda Division','Paternal',3,2,'victoria'));
encuentrosHistorico.push(new partHistoria('19.06.1948','Ferro Carril Oeste','Segunda Division','Remedios de Escalada',2,2,'empate'));
encuentrosHistorico.push(new partHistoria('26.06.1948','Los Andes','Segunda Division','Lomas de Zamora',2,0,'victoria'));
encuentrosHistorico.push(new partHistoria('17.07.1948','Central Córdoba (Ros)','Segunda Division','Remedios de Escalada',2,1,'victoria'));
encuentrosHistorico.push(new partHistoria('24.07.1948','Argentino de Rosario','Segunda Division','Rosario',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('31.07.1948','Defensores de Belgrano','Segunda Division','Remedios de Escalada',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('07.08.1948','Estudiantes (Bs.As.)','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('14.08.1948','Temperley','Segunda Division','Temperley',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('28.08.1948','Tiro Federal','Segunda Division','Remedios de Escalada',4,0,'victoria'));
encuentrosHistorico.push(new partHistoria('04.09.1948','All Boys','Segunda Division','Floresta',3,1,'victoria'));
encuentrosHistorico.push(new partHistoria('11.09.1948','Argentinos Juniors','Segunda Division','Remedios de Escalada',4,1,'victoria'));
encuentrosHistorico.push(new partHistoria('18.09.1948','Ferro Carril Oeste','Segunda Division','Caballito',3,3,'empate'));
encuentrosHistorico.push(new partHistoria('02.10.1948','Los Andes','Segunda Division','Remedios de Escalada',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('10.10.1948','Central Córdoba (Ros)','Segunda Division','Rosario',0,2,'derrota'));
encuentrosHistorico.push(new partHistoria('16.10.1948','Argentino de Rosario','Segunda Division','Remedios de Escalada',4,2,'victoria'));
encuentrosHistorico.push(new partHistoria('23.10.1948','Defensores de Belgrano','Segunda Division','Núñez',1,2,'derrota'));
encuentrosHistorico.push(new partHistoria('30.10.1948','Tiro Federal','Segunda Division - Ascenso','Belgrano',0,0,'empate'));
encuentrosHistorico.push(new partHistoria('13.11.1948','Nueva Chicago','Segunda Division - Ascenso','Parque Patricios',2,3,'derrota'));
encuentrosHistorico.push(new partHistoria('20.11.1948','Ferro Carril Oeste','Segunda Division - Ascenso','Banfield',1,0,'victoria'));
encuentrosHistorico.push(new partHistoria('27.11.1948','Dock Sud','Segunda Division - Ascenso','Lanús',1,4,'derrota'));
encuentrosHistorico.push(new partHistoria('04.12.1948','Defensores de Belgrano','Segunda Division - Ascenso','Belgrano',2,5,'derrota'));
encuentrosHistorico.push(new partHistoria('11.12.1948','Atlanta','Segunda Division - Ascenso','Avellaneda',0,7,'derrota'));
encuentrosHistorico.push(new partHistoria('18.12.1948','Argentinos Juniors','Segunda Division - Ascenso','Belgrano',1,5,'derrota'));
